
// -----------------------------------------------------------------------------
// SOLID WASTE TOPIC 4 REVISION APP
// Exhaustive 6-Day Data
// -----------------------------------------------------------------------------

// --- DOM ELEMENTS ---
const elements = {
  dayLinks: document.querySelectorAll('.sidebar-day-link'),
  dayTabs: document.querySelectorAll('.day-tab'),
  dayPanels: document.querySelectorAll('.day-panel'),
  
  // Progress
  progressBar: document.getElementById('sidebar-progress-bar'),
  progressPercentage: document.querySelector('.progress-percentage'),
  badgeTitle: document.getElementById('overall-badge-title'),
  daysCompletedCount: document.getElementById('days-completed-count'),
  avgQuizScore: document.getElementById('avg-quiz-score'),
  
  // Flashcards
  fcTitle: document.getElementById('flashcard-card-title-text'),
  fcFront: document.getElementById('flashcard-front-content'),
  fcBack: document.getElementById('flashcard-back-content'),
  fcPrevBtn: document.getElementById('flashcard-prev-btn'),
  fcNextBtn: document.getElementById('flashcard-next-btn'),
  fcShuffleBtn: document.getElementById('flashcard-shuffle-btn'),
  fcIndicator: document.getElementById('flashcard-position-indicator'),
  fcArena: document.getElementById('revision-flashcard-arena'),
  
  // Quiz
  quizTitle: document.getElementById('quiz-day-title'),
  quizContainer: document.getElementById('quiz-body-area'),
  
  // Checkboxes
  completionCheckboxes: document.querySelectorAll('input[id^="complete-day-checkbox"]')
};

// --- STATE ---
let currentDay = 1;
let fcIndex = 0;
let currentFlashcards = [];
let shuffledFlashcards = [];
let isFcFlipped = false;

// --- DATA: FLASHCARDS ---
const revisionData = {
  1: {
    flashcards: [
      { f: "What is the 5Rs framework mentioned in the Sustainable Waste Management Act (2022)?", b: "Reduce, Reuse, Recycle, Repair, Refurbish." },
      { f: "What is Garbage?", b: "Putrescible (rotting) animal and vegetable waste from food handling that produces obnoxious odors." },
      { f: "What is the difference between combustible and non-combustible waste?", b: "Combustible: burns easily (paper, rubber). Non-combustible: does not burn (glass, tin, dirt)." },
      { f: "What are bulky wastes?", b: "Large appliances (fridges, furniture, tires) requiring special collection mechanisms." },
      { f: "What makes waste 'hazardous'?", b: "Ignitability, corrosivity, reactivity, and toxicity. Includes solvents, paints, and medical path-wastes." }
    ],
    quiz: [
      { q: "Which category does leftover food and vegetable peels from apartments fall under?", opts: ["Institutional", "Residential", "Industrial", "Municipal"], a: 1 },
      { q: "What distinguishes 'Garbage' from general refuse?", opts: ["It only contains glass", "It is exclusively generated by industries", "It contains highly putrescible organic matter that attracts rats", "It cannot be safely buried"], a: 2 },
      { q: "Which 'R' is NOT part of the 5Rs in the Sustainable Waste Management Act?", opts: ["Repair", "Refuse", "Refurbish", "Reuse"], a: 1 },
      { q: "Which type of waste includes dust, building debris, and street cleaning residue?", opts: ["Institutional", "Residential", "Municipal", "Agricultural"], a: 2 },
      { q: "Ashes and residues from burning wood and coal are valuable where?", opts: ["In compost heaps", "In sanitary landfills", "In incinerators", "In biodigesters"], a: 1 }
    ]
  },
  2: {
    flashcards: [
      { f: "What is a Solid Waste Management (SWM) System?", b: "A combination of functional elements to collect and dispose of waste at minimal cost while preserving public health." },
      { f: "What is the maximum time heterogeneous waste should be stored in residential areas before removal?", b: "8 days, due to shortage of storage and the rotting of biodegradable materials." },
      { f: "What is a transfer station?", b: "An intermediate station where waste from smaller collection vehicles is transferred to larger ones for long-distance transport." },
      { f: "What does 'Processing' involve in SWM?", b: "Altering the physical and chemical characteristics of waste through compaction, thermal reduction, or composting." },
      { f: "What is the ultimate fate of all solid wastes?", b: "Waste disposal, typically in modern sanitary landfills." }
    ],
    quiz: [
      { q: "Within how many days must heterogeneous wastes in residential areas be removed?", opts: ["2 days", "8 days", "14 days", "30 days"], a: 1 },
      { q: "What is the most important aspect of the 'Waste generation' element?", opts: ["Transportation", "Incineration", "Identification of waste", "Burning"], a: 2 },
      { q: "What equipment is used in the 'Recovery' stage to separate iron?", opts: ["Air classifier", "Screens", "Magnetic device", "Incinerator"], a: 2 },
      { q: "Where are wastes from smaller vehicles transferred to larger ones?", opts: ["Processing plant", "Transfer station", "Landfill cell", "Hopper"], a: 1 },
      { q: "Which functional element relies heavily on 'land use planning' as a primary determinant?", opts: ["Waste disposal", "Waste storage", "Processing", "Generation"], a: 0 }
    ]
  },
  3: {
    flashcards: [
      { f: "What is incineration?", b: "The combustion of organic substances in waste, converting it into ash, flue gas, and heat." },
      { f: "What does the secondary chamber in an incinerator do?", b: "It breaks down remaining pollutants and gases from the primary combustion." },
      { f: "What is a Rotary Kiln Incinerator?", b: "A slanted rotating chamber that keeps waste circulating continually. Great for medical and hazardous waste." },
      { f: "How does a Fluidized Bed Incinerator work?", b: "Air is injected into a bed of granular material (sand) to make it violently agitate like a fluid. Very high thermal efficiency (90%)." },
      { f: "What is a Moving Grate Incinerator?", b: "Waste is burned in layers on a moving grate. Bottom ash falls into a water trap as slag (10-25% of weight)." }
    ],
    quiz: [
      { q: "Which incinerator type operates by injecting air into a bed of granular material like limestone or sand?", opts: ["Rotary Kiln", "Moving Grate", "Fluidized Bed", "Multiple Hearth"], a: 2 },
      { q: "What prevents smoke and fumes from being misdirected back into the building from an incinerator?", opts: ["A heavy iron lid", "Negative pressure created by a fan", "A water trap", "Electrostatic precipitators"], a: 1 },
      { q: "Which incinerator type is best suited for medical waste and features a rotating chamber?", opts: ["Rotary Kiln", "Liquid Injection", "Catalytic", "Fixed Grate"], a: 0 },
      { q: "What is the purpose of the Air Pollution Control Devices (like scrubbers)?", opts: ["To generate electricity", "To remove pollutants from flue gases before they enter the atmosphere", "To dry the waste before burning", "To cool the ash"], a: 1 },
      { q: "Which type of incinerator uses a catalyst to limit nitrogen oxide emissions at lower temperatures?", opts: ["Multiple Hearth", "Waste-Gas Flare", "Moving Grate", "Catalytic"], a: 3 }
    ]
  },
  4: {
    flashcards: [
      { f: "How much does incineration reduce the total amount of garbage?", b: "By up to 95% total, and the solid portion by 80-85%." },
      { f: "What is 'Waste-to-Energy' in incineration?", b: "Waste is converted into heat or power (electricity)." },
      { f: "What is a major demerit of incinerators regarding air pollution?", b: "They can produce nitrogen oxides (NOx), sulfur oxides, and toxic particulate matter." },
      { f: "Why are incinerators considered better for odor than landfills?", b: "Waste is burned inside a regulated facility instead of degrading in the open air." },
      { f: "Do incinerators produce methane?", b: "No, making them safer and better for greenhouse gas impacts compared to landfills." }
    ],
    quiz: [
      { q: "What percentage can incinerators reduce the total amount of garbage by?", opts: ["50%", "75%", "95%", "100%"], a: 2 },
      { q: "Which of the following is a major disadvantage of incineration?", opts: ["It requires a lot of land space", "It emits high amounts of methane", "It produces bottom ash and fly ash containing harmful metals", "It cannot destroy pathogens"], a: 2 },
      { q: "Unlike landfills, incinerators are capable of doing what with the waste?", opts: ["Converting it into compost", "Converting it into energy (heat/electricity)", "Transforming it into clean drinking water", "Eliminating 100% of the solid residue"], a: 1 },
      { q: "Why can incinerator facilities be located closer to towns than landfills?", opts: ["They are aesthetically beautiful", "They require less space and have regulated odors", "They make no noise", "They do not require trucks for delivery"], a: 1 },
      { q: "Is incineration considered a 'sustainable' waste management solution?", opts: ["Yes, completely", "No, because it does not conserve resources", "Yes, because it recycles metals", "No, because it uses too much water"], a: 1 }
    ]
  },
  5: {
    flashcards: [
      { f: "What is a refuse chute?", b: "A vertical pipe system passing from floor to floor for receiving refuse in a multi-story building." },
      { f: "What diameter should a standard chute shaft be?", b: "400mm." },
      { f: "What is the fire resistance requirement for the chute collection chamber?", b: "1-hour fire resistance." },
      { f: "What is an Inlet Hopper?", b: "The receptacle fitting on each floor for dropping refuse into the chute." },
      { f: "What is a major risk of single chutes used for mixed waste?", b: "Cross-contamination, which compromises recycling efforts." }
    ],
    quiz: [
      { q: "What is the standard recommended diameter for a refuse chute shaft?", opts: ["200mm", "400mm", "600mm", "1000mm"], a: 1 },
      { q: "What feature must the Collection Chamber have to prevent foul smells from rising?", opts: ["A 100mm diameter trap", "A refrigerator", "An incinerator", "A vacuum pump"], a: 0 },
      { q: "What is the fire resistance requirement for the structure containing the chute void?", opts: ["30 minutes", "1 hour", "2 hours", "4 hours"], a: 1 },
      { q: "Which type of chute is specifically integrated with a device to compress waste and save space?", opts: ["Recycling Chute", "Angled Chute", "Compactor Chute", "Odour-Control Chute"], a: 2 },
      { q: "The chute should not be located more than what horizontal distance from each dwelling?", opts: ["10 meters", "20 meters", "30 meters", "50 meters"], a: 2 }
    ]
  },
  6: {
    flashcards: [
      { f: "How does the Garchey system collect waste?", b: "Through a large plug in a unit directly below the kitchen sink." },
      { f: "How is waste removed in the Garchey system?", b: "A specially equipped tanker collects it weekly, compacting it into a semi-solid mass." },
      { f: "What is the ideal daily soil cover depth for a sanitary landfill?", b: "0.5 meters of excavated soil." },
      { f: "What is a refuse cell in a landfill?", b: "A confined portion where refuse is spread and compacted in thin layers up to 3m deep." },
      { f: "What is leachate?", b: "A toxic liquid that seeps from decomposing waste in a landfill, potentially contaminating groundwater." }
    ],
    quiz: [
      { q: "In the Garchey system, where is the refuse initially placed by the user?", opts: ["In a communal bin room", "Inside a central tube below the kitchen sink", "In a basement compactor", "On the balcony"], a: 1 },
      { q: "How much soil should ideally cover deposited refuse at the end of the day in a landfill?", opts: ["0.1m", "0.5m", "1.5m", "3m"], a: 1 },
      { q: "What is the basic operational element of a sanitary landfill called?", opts: ["A trench", "A refuse cell", "A hopper", "A slag pit"], a: 1 },
      { q: "What major environmental hazard is uniquely associated with landfills leaking toxic liquid into groundwater?", opts: ["Fly ash", "Slag", "Leachate", "Flue gas"], a: 2 },
      { q: "Which of the following is a disadvantage of the Garchey system?", opts: ["It increases vermin", "It takes up an entire kitchen cabinet space", "It requires daily manual emptying by the resident", "It smells worse than open bins"], a: 1 }
    ]
  }
};

// --- INITIALIZATION ---
function initApp() {
  attachDayNavigation();
  attachCheckboxes();
  attachFlashcardControls();
  
  // Custom Engineering Sandbox Tabs
  document.getElementById('calc-tab-fall').addEventListener('click', (e) => {
    e.target.classList.add('active');
    document.getElementById('calc-tab-gradient').classList.remove('active');
    document.getElementById('calc-form-head').style.display = 'flex';
    document.getElementById('calc-form-flow').style.display = 'none';
  });
  
  document.getElementById('calc-tab-gradient').addEventListener('click', (e) => {
    e.target.classList.add('active');
    document.getElementById('calc-tab-fall').classList.remove('active');
    document.getElementById('calc-form-flow').style.display = 'flex';
    document.getElementById('calc-form-head').style.display = 'none';
  });
  
  // Realtime calc logic
  document.querySelectorAll('.calc-input').forEach(inp => {
    inp.addEventListener('input', updateCalculator);
  });
  
  loadDayContent(1);
  updateGlobalProgress();
}

// --- NAVIGATION ---
function attachDayNavigation() {
  const switchDay = (dayStr) => {
    const day = parseInt(dayStr);
    currentDay = day;
    loadDayContent(day);
  };
  elements.dayLinks.forEach(link => {
    link.addEventListener('click', () => switchDay(link.dataset.day));
  });
  elements.dayTabs.forEach(tab => {
    tab.addEventListener('click', () => switchDay(tab.dataset.day));
  });
}

function loadDayContent(day) {
  elements.dayLinks.forEach(l => l.classList.remove('active'));
  elements.dayTabs.forEach(t => t.classList.remove('active'));
  elements.dayPanels.forEach(p => p.classList.remove('active'));
  
  document.getElementById(`nav-day-${day}`).classList.add('active');
  document.getElementById(`tab-day-${day}`).classList.add('active');
  document.getElementById(`day-panel-${day}`).classList.add('active');
  
  document.getElementById('dashboard-main').scrollTop = 0;
  
  loadFlashcardsForDay(day);
  loadQuizForDay(day);
}

// --- CHECKBOX & PROGRESS ---
function attachCheckboxes() {
  elements.completionCheckboxes.forEach(cb => {
    cb.addEventListener('change', () => {
      const dayPanel = cb.closest('.day-panel');
      const dayId = dayPanel.id.split('-')[2];
      
      if(cb.checked) {
        document.getElementById(`nav-day-${dayId}`).innerHTML += ' <i class="ri-check-line" style="color:var(--color-success)"></i>';
        document.getElementById(`tab-day-${dayId}`).classList.add('completed');
      } else {
        const icon = document.getElementById(`nav-day-${dayId}`).querySelector('.ri-check-line');
        if(icon) icon.remove();
        document.getElementById(`tab-day-${dayId}`).classList.remove('completed');
      }
      updateGlobalProgress();
    });
  });
}

function updateGlobalProgress() {
  let completed = 0;
  elements.completionCheckboxes.forEach(cb => {
    if(cb.checked) completed++;
  });
  
  const total = 6;
  const pct = Math.round((completed / total) * 100);
  
  elements.progressBar.style.width = pct + '%';
  elements.progressPercentage.textContent = pct + '%';
  elements.daysCompletedCount.textContent = completed;
  
  if (pct === 100) {
    elements.badgeTitle.textContent = "Waste Master";
    elements.badgeTitle.style.color = "var(--color-primary)";
  } else if (pct > 50) {
    elements.badgeTitle.textContent = "Senior Apprentice";
  } else {
    elements.badgeTitle.textContent = "Junior Apprentice";
  }
}

// --- FLASHCARDS ---
function attachFlashcardControls() {
  elements.fcArena.addEventListener('click', () => {
    isFcFlipped = !isFcFlipped;
    if (isFcFlipped) {
      elements.fcArena.classList.add('flipped');
      elements.fcTitle.textContent = "Concept Definition";
    } else {
      elements.fcArena.classList.remove('flipped');
      elements.fcTitle.textContent = "Tap to Reveal";
    }
  });

  elements.fcPrevBtn.addEventListener('click', () => {
    if (fcIndex > 0) {
      fcIndex--;
      renderCurrentFlashcard();
    }
  });
  
  elements.fcNextBtn.addEventListener('click', () => {
    if (fcIndex < currentFlashcards.length - 1) {
      fcIndex++;
      renderCurrentFlashcard();
    }
  });

  elements.fcShuffleBtn.addEventListener('click', () => {
    shuffledFlashcards = [...currentFlashcards].sort(() => Math.random() - 0.5);
    currentFlashcards = shuffledFlashcards;
    fcIndex = 0;
    renderCurrentFlashcard();
  });
}

function loadFlashcardsForDay(day) {
  const data = revisionData[day];
  if(data && data.flashcards) {
    currentFlashcards = [...data.flashcards];
    fcIndex = 0;
    renderCurrentFlashcard();
  }
}

function renderCurrentFlashcard() {
  if(currentFlashcards.length === 0) return;
  const fc = currentFlashcards[fcIndex];
  
  isFcFlipped = false;
  elements.fcArena.classList.remove('flipped');
  elements.fcTitle.textContent = "Tap to Reveal";
  
  elements.fcFront.innerHTML = fc.f;
  elements.fcBack.innerHTML = fc.b;
  
  elements.fcIndicator.textContent = `${fcIndex + 1} / ${currentFlashcards.length}`;
  
  elements.fcPrevBtn.disabled = (fcIndex === 0);
  elements.fcNextBtn.disabled = (fcIndex === currentFlashcards.length - 1);
}

// --- QUIZ ---
let quizAnswers = {};

function loadQuizForDay(day) {
  elements.quizTitle.innerHTML = `<i class="ri-questionnaire-line"></i> Day ${day} Revision Quiz`;
  const data = revisionData[day];
  const container = elements.quizContainer;
  container.innerHTML = '';
  
  if(!data || !data.quiz) {
    container.innerHTML = "<p>No quiz available for this day.</p>";
    return;
  }
  
  quizAnswers[day] = {};
  
  data.quiz.forEach((q, idx) => {
    const qDiv = document.createElement('div');
    qDiv.className = 'quiz-question';
    
    let html = `<h4>Q${idx + 1}: ${q.q}</h4><div class="quiz-options">`;
    q.opts.forEach((opt, optIdx) => {
      html += `
        <label class="quiz-option-label" id="opt-lbl-${day}-${idx}-${optIdx}">
          <input type="radio" name="quiz-${day}-q${idx}" value="${optIdx}">
          ${opt}
        </label>
      `;
    });
    html += `</div>
             <div class="quiz-feedback" id="quiz-fb-${day}-${idx}" style="display:none; font-size: 0.8rem; margin-top: 0.5rem; padding: 0.5rem; border-radius: 4px;"></div>`;
    
    qDiv.innerHTML = html;
    container.appendChild(qDiv);
    
    const radios = qDiv.querySelectorAll('input[type="radio"]');
    radios.forEach(radio => {
      radio.addEventListener('change', (e) => {
        handleQuizAnswer(day, idx, parseInt(e.target.value), q.a);
      });
    });
  });
}

function handleQuizAnswer(day, qIdx, selectedIdx, correctIdx) {
  quizAnswers[day][qIdx] = (selectedIdx === correctIdx);
  
  const fb = document.getElementById(`quiz-fb-${day}-${qIdx}`);
  const labels = document.querySelectorAll(`input[name="quiz-${day}-q${qIdx}"]`);
  
  labels.forEach((r, i) => {
    const lbl = document.getElementById(`opt-lbl-${day}-${qIdx}-${i}`);
    lbl.style.background = 'rgba(255, 255, 255, 0.05)';
    lbl.style.borderColor = 'rgba(0,0,0,0.1)';
  });
  
  const selLabel = document.getElementById(`opt-lbl-${day}-${qIdx}-${selectedIdx}`);
  
  if (selectedIdx === correctIdx) {
    fb.style.display = 'block';
    fb.style.background = 'rgba(16, 185, 129, 0.1)';
    fb.style.color = 'var(--color-success)';
    fb.innerHTML = '<i class="ri-checkbox-circle-line"></i> Correct!';
    selLabel.style.borderColor = 'var(--color-success)';
    selLabel.style.background = 'rgba(16, 185, 129, 0.05)';
  } else {
    fb.style.display = 'block';
    fb.style.background = 'rgba(239, 68, 68, 0.1)';
    fb.style.color = 'var(--color-danger)';
    fb.innerHTML = '<i class="ri-close-circle-line"></i> Incorrect. Try again.';
    selLabel.style.borderColor = 'var(--color-danger)';
    selLabel.style.background = 'rgba(239, 68, 68, 0.05)';
  }
  
  recalcAvgQuizScore();
}

function recalcAvgQuizScore() {
  let totalQs = 0;
  let totalCorrect = 0;
  
  for(let d in quizAnswers) {
    for(let q in quizAnswers[d]) {
      totalQs++;
      if(quizAnswers[d][q]) totalCorrect++;
    }
  }
  
  if(totalQs === 0) return;
  const pct = Math.round((totalCorrect / totalQs) * 100);
  elements.avgQuizScore.textContent = pct + '%';
  
  if(pct >= 80) {
    elements.avgQuizScore.style.color = 'var(--color-success)';
  } else if (pct >= 50) {
    elements.avgQuizScore.style.color = 'var(--color-warning)';
  } else {
    elements.avgQuizScore.style.color = 'var(--text-main)';
  }
}

// --- SANDBOX CALC ---
function updateCalculator() {
  const isFall = document.getElementById('calc-tab-fall').classList.contains('active');
  const resVal = document.getElementById('calc-result-val');
  const resSub = document.getElementById('calc-result-sub');
  
  if(isFall) {
    const l = parseFloat(document.getElementById('calc-input-height').value) || 0;
    const g = parseFloat(document.getElementById('calc-input-density').value) || 40;
    
    // Fall = Length / Gradient
    const fall_m = l / g;
    const fall_mm = fall_m * 1000;
    
    resVal.textContent = fall_m.toFixed(3) + " m";
    resSub.innerHTML = `Equivalent to <strong>${fall_mm.toFixed(0)} mm</strong> fall.<br>Fall = Length / Gradient.`;
  } else {
    const l = parseFloat(document.getElementById('calc-input-q').value) || 0;
    const f = parseFloat(document.getElementById('calc-input-velocity').value) || 1;
    
    // Gradient = Length / Fall
    const g = l / f;
    
    resVal.textContent = "1 in " + g.toFixed(1);
    resSub.innerHTML = `Pipe requires a slope of 1 in ${g.toFixed(0)}.<br>Gradient = Length / Fall`;
  }
}

// Startup
document.addEventListener('DOMContentLoaded', initApp);
